package com.myapplication.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.myapplication.model.Custom;
import com.myapplication.model.Student;

import com.myapplication.greendao.CustomDao;
import com.myapplication.greendao.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig customDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final CustomDao customDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        customDaoConfig = daoConfigMap.get(CustomDao.class).clone();
        customDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        customDao = new CustomDao(customDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(Custom.class, customDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        customDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public CustomDao getCustomDao() {
        return customDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
